### ISSUE TITLE
Handle name clashes

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/painless#2]
We probably need to make sure that parameter names are unique. In a single scope, this is enforced by the compiler. However, nothing is currently preventing the user to create multiple parameters with the same name in different scopes.

We would probably need a central "parameter library" class (singleton?) that keeps track of all registered parameters.

**Comment by hmenke** [comment]
File locking? https://linux.die.net/man/3/lockf

**Comment by sharkdp** [comment]
Thank you for the feedback. Interesting idea!

I thought about this some more. I now think that I actually *want* to be able to have name duplicates. This allows users to easily share a common parameter in different places of their code without having to create a global object.

In principle, everything works just expected right now. I can even open multiple processes that share the same parameter. That might sound strange at first, but I actually have a very good use case for this. Also, I wouldn't want to add the executable name or PID anywhere in the parameter file path.

The only thing that is not really "clean" right now is that we will create the initial parameter file multiple times. That doesn't cause any problem if all of these parameters are created at the same time (program start), but it would be annoying if a parameter appears somewhere later in the same process.

In order to solve this, we could simply keep a list of all parameters (in the current process) and skip writing of the initial file if a parameter is already in that list.
